// src/components/ui/app-header.tsx
import { Component, createMemo, Match, Switch } from "solid-js"
import { accent, cycleAccent, cycleTheme, theme } from "~/lib/theme"
import tooltip from "~/lib/tooltip"
import MdiArrowLeftTop from "~icons/mdi/arrow-left-top"
import MdiCircle from "~icons/mdi/circle"
import MdiBrightnessAuto from "~icons/mdi/brightness-auto"
import MdiBrightness4 from "~icons/mdi/brightness-4"
import MdiBrightness7 from "~icons/mdi/brightness-7"

tooltip

const AppHeader: Component<{ showBackButton: boolean }> = (props) => {
  const themeBtnTitle = createMemo(() => {
    if (theme() == "dark") return "Dark theme"
    else if (theme() == "light") return "Light theme"
    else return "System theme"
  })
  const accentBtnTitle = createMemo(() => accent()[0].toUpperCase() + accent().substring(1) + " accent")

  return (
    <header class="container max-w-4xl flex items-center p-3">
      {props.showBackButton &&
        <a href="/" class="btn btn-icon" use:tooltip={[() => "Go Home", "right"]}>
          <MdiArrowLeftTop />
        </a>
      }
      <div class="flex-grow" />
      <button
        class="btn btn-icon"
        onClick={cycleAccent}
        use:tooltip={[accentBtnTitle, "bottom"]}
      ><MdiCircle class="text-accent" /></button>
      <button
        class="btn btn-icon"
        onClick={cycleTheme}
        use:tooltip={[themeBtnTitle, "bottom"]}
      >
        <Switch>
          <Match when={theme() == "dark"}><MdiBrightness4 /></Match>
          <Match when={theme() == "light"}><MdiBrightness7 /></Match>
          <Match when={theme() == null}><MdiBrightnessAuto /></Match>
        </Switch>
      </button>
    </header>
  )
}

export default AppHeader

// src/components/AppHeader.vue
<script lang="ts" setup>
import { useDarkMode } from "@/hooks"
const { isDark, toggleDark } = useDarkMode()
</script>

<template>
  <header class="container px-6 py-12 flex items-center gap-2">
    <router-link to="/" class="text-lg no-underline inline-block mr-auto">Gianni Tumedei</router-link>
    <button class="btn icon" title="Change language">
      <mdi-translate class="text-secondary"/>
    </button>
    <button
      class="btn icon"
      :title="isDark ? 'Enable light theme' : 'Enable dark theme'"
      @click="() => toggleDark()"
    >
      <mdi-brightness-7 v-if="isDark" class="text-secondary"/>
      <mdi-brightness-4 v-else class="text-secondary"/>
    </button>
  </header>
</template>

<style lang="postcss">

.clip { @apply
  fixed top-0 left-0 bottom-0 right-0
  bg-primary transition transition-all;
}

</style>
