// src/components/ui/back-to-top-button.tsx
import { Component, createSignal, onCleanup, onMount } from "solid-js"
import { Transition } from "solid-transition-group"
import { useTippy } from "~/composables/tippy"
import MdiMenuUpOutline from "~icons/mdi/menu-up-outline"

const BackToTopButton: Component = () => {
  const onClick = () => window.scrollTo({ top: 0, behavior: "smooth" })

  const [show, setShow] = createSignal(false)

  const onScroll = () => setShow(window.scrollY > 200)
  onMount(() => document.addEventListener("scroll", onScroll))
  onCleanup(() => document.removeEventListener("scroll", onScroll))

  const btn = (
    <button class="btn fab inverted" onClick={onClick}>
      <MdiMenuUpOutline />
    </button>
  )

  useTippy(btn, () => "Go back to top", "left")

  return (
    <div class="fixed bottom-6 right-6">
      <Transition name="fade">
        {show() && btn}
      </Transition>
    </div>
  )
}

export default BackToTopButton

// src/components/back-to-top-button.vue
<script lang="ts" setup>
import { ref } from "vue"
import { useEventListener } from "@vueuse/core"
import Icon from "@/components/icon.vue"
import { useTippy } from "@/composables"

const show = ref(false)
useEventListener(document, "scroll", () => show.value = window.scrollY > 200)

const backToTopButton = ref<HTMLButtonElement>()
useTippy(backToTopButton, "ui.back_to_top_btn_title", "left")

const onClick = () => window.scrollTo({ top: 0, behavior: "smooth" })
</script>

<template>
  <div class="fixed bottom-6 right-6">
    <transition name="fade">
      <button
        v-show="show"
        ref="backToTopButton"
        class="btn fab inverted"
        @click="onClick"
      ><icon name="mdi:menu-up-outline"/></button>
    </transition>
  </div>
</template>
