// src/components/app-footer.vue
<script lang="ts" setup>
import Icon from "@/components/icon.vue"

const year = new Date().getFullYear()
</script>

<template>
  <footer class="container text-sm text-center pt-18 pb-12">
    <p class="inline-flex items-center"><icon name="mdi:copyright" class="!text-sm mr-1"/> {{year}} · Gianni Tumedei</p>
  </footer>
</template>

// src/components/ui/app-footer.tsx
import type { Component } from "solid-js"
import MdiCopyright from "~icons/mdi/copyright"

const Footer: Component = () => {
  const year = new Date().getFullYear()
  return (
    <footer class="w-full flex flex-col items-center bg-primary-dark">
      <div class="container text-sm text-center py-11">
        <p class="inline-flex items-center"><MdiCopyright class="!text-sm mr-1" /> {year} · Gianni Tumedei</p>
      </div>
    </footer>
  )
}

export default Footer
