// src/components/ui/loading-spinner.vue
<script lang="ts" setup>
withDefaults(
  defineProps<{ inverted: boolean }>(),
  { inverted: false }
)
</script>

<template>
  <div :class="`spinner ${inverted ? 'bg-inverted-typography-base' : 'bg-typography-base'}`"></div>
</template>

<style lang="postcss" scoped>

.spinner { @apply
  h-5 w-5 rounded-full;
  animation: scaleout 1.0s infinite ease-in-out;
}

@keyframes scaleout {

  0% {
    transform: scale(0);
  }

  100% {
    transform: scale(1.0);
    opacity: 0;
  }
}

</style>

// src/components/ui/loading-spinner.tsx
import type { Component } from "solid-js"

const LoadingSpinner: Component<{ inverted?: boolean }> = (props) => {
  return (
    <>
      <div class={`spinner h-5 w-5 rounded-full ${props.inverted ? "bg-inverted-typography-base" : "bg-typography-base"}`} />

      <style>{`
        .spinner {
          animation: scaleout 1.0s infinite ease-in-out;
        }

        @keyframes scaleout {
          0% {
            transform: scale(0);
          }
          100% {
            transform: scale(1.0);
            opacity: 0;
          }
        }
      `}</style>
    </>
  )
}

export default LoadingSpinner
